# Generated by Django 6.0.8 on 2026-09-19 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('llm', '0002_llmbatch_agent_run_llmcall_agent_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('product', 'Product Information'), ('audience', 'Target Audience'), ('brand_voice', 'Brand Voice'), ('competitors', 'Competitor Analysis'), ('content_strategy', 'Content Strategy'), ('compliance', 'Compliance Guidelines')], max_length=30)),
                ('content_md', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('ai', 'Ai'), ('human', 'Human'), ('template', 'Template')], default='ai', max_length=20)),
                ('prompt_version', models.CharField(blank=True, max_length=20)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='ContextDocumentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_md', models.TextField()),
                ('source', models.CharField(choices=[('ai', 'Ai'), ('human', 'Human'), ('template', 'Template')], max_length=20)),
                ('prompt_version', models.CharField(blank=True, max_length=20)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='context.contextdocument')),
                ('llm_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='llm.llmcall')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CrawledPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('content_text', models.TextField()),
                ('content_hash', models.CharField(max_length=64)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.project')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='contextdocument',
            constraint=models.UniqueConstraint(fields=('project', 'kind'), name='uniq_doc_kind'),
        ),
        migrations.AddConstraint(
            model_name='crawledpage',
            constraint=models.UniqueConstraint(fields=('project', 'url'), name='uniq_page_url'),
        ),
    ]
