# Generated by Django 6.0.8 on 2026-09-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextdocument',
            name='prompt_version',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='contextdocumentrevision',
            name='prompt_version',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
