# Generated by Django 6.0.8 on 2026-09-19 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('onboarding', 'Onboarding'), ('recrawl', 'Recrawl'), ('regenerate_doc', 'Regenerate Doc'), ('reddit', 'Reddit'), ('content', 'Content'), ('x', 'X'), ('regenerate_draft', 'Regenerate Draft')], max_length=30)),
                ('trigger', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('waiting_batch', 'Waiting Batch'), ('succeeded', 'Succeeded'), ('partial', 'Partial'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('current_step', models.CharField(blank=True, max_length=255)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RunEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('message', models.CharField(max_length=500)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='agents.agentrun')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('reddit', 'Reddit'), ('content', 'Content'), ('x', 'X')], max_length=20)),
                ('enabled', models.BooleanField(default=False)),
                ('cron', models.CharField(default='0 */6 * * *', max_length=100)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('publish_mode', models.CharField(choices=[('manual', 'Manual')], default='manual', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_configs', to='core.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'agent_type'), name='uniq_agent_per_project')],
            },
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['project', 'kind', '-created_at'], name='agents_agen_project_eb5ff2_idx'),
        ),
    ]
