# Generated by Django 6.0.8 on 2026-09-19 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=30)),
                ('purpose', models.CharField(max_length=50)),
                ('resource_id', models.CharField(blank=True, max_length=200)),
                ('external_run_id', models.CharField(blank=True, max_length=100)),
                ('items', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('agent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_usage', to='agents.agentrun')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_usage', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
