# Generated by Django 6.0.8 on 2026-09-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_externalusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalusage',
            name='duration_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='externalusage',
            name='status',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
