# Generated by Django 6.0.8 on 2026-09-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0003_externalusage_duration_ms_externalusage_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentrun",
            name="kind",
            field=models.CharField(
                choices=[
                    ("onboarding", "Onboarding"),
                    ("recrawl", "Recrawl"),
                    ("regenerate_doc", "Regenerate Doc"),
                    ("reddit", "Reddit"),
                    ("content", "Content"),
                    ("x", "X"),
                    ("regenerate_draft", "Regenerate Draft"),
                    ("digest_feedback", "Digest Feedback"),
                ],
                max_length=30,
            ),
        ),
    ]
