# Generated by Django 6.0.9 on 2026-10-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0004_alter_agentrun_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentconfig",
            name="draft_model",
            field=models.CharField(default="sonnet", max_length=20),
        ),
    ]
