# Generated by Django 6.0.8 on 2026-09-19 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack', models.CharField(default='general', max_length=50)),
                ('source', models.CharField(choices=[('default', 'Default'), ('suggested', 'Suggested'), ('user', 'User')], default='default', max_length=20)),
                ('author_role', models.CharField(default='founder', help_text='Who posts the drafts, e.g. founder, CEO, marketing lead', max_length=60)),
                ('rules', models.JSONField(default=list)),
                ('disclosure', models.CharField(default="(Disclosure: I'm the {role} of {project}.)", help_text='Affiliation disclosure; {role} and {project} are filled in', max_length=300)),
                ('blog_disclaimer', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_policy', to='core.project')),
            ],
        ),
    ]
