# Generated by Django 6.0.8 on 2026-09-19 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0002_externalusage'),
        ('core', '0001_initial'),
        ('llm', '0002_llmbatch_agent_run_llmcall_agent_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('angle', models.TextField(blank=True)),
                ('target_keywords', models.JSONField(blank=True, default=list)),
                ('pillar', models.CharField(blank=True, max_length=200)),
                ('why', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('drafted', 'Drafted'), ('rejected', 'Rejected')], db_index=True, default='proposed', max_length=20)),
                ('requested_by_user', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_topics', to='agents.agentrun')),
                ('llm_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='llm.llmcall')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_topics', to='core.project')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
