# Generated by Django 6.0.8 on 2026-09-30 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_waitlistsignup"),
        ("inbox", "0004_draft_dismissed_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agent_type", models.CharField(max_length=20)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("explicit", "Explicit"),
                            ("instruction", "Instruction"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        blank=True,
                        choices=[("up", "Up"), ("down", "Down")],
                        max_length=10,
                    ),
                ),
                ("text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("digested_at", models.DateTimeField(blank=True, null=True)),
                (
                    "draft",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback",
                        to="inbox.draft",
                    ),
                ),
                (
                    "draft_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="inbox.draftversion",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_feedback",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "agent_type", "digested_at"],
                        name="feedback_ag_project_063251_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AgentLearnings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agent_type", models.CharField(max_length=20)),
                ("writing_md", models.TextField(blank=True)),
                ("selection_md", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("ai", "Ai"), ("human", "Human")],
                        default="ai",
                        max_length=10,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_learnings",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "agent_type"),
                        name="uniq_learnings_per_agent",
                    )
                ],
            },
        ),
    ]
