# Generated by Django 6.0.8 on 2026-09-19 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0002_externalusage'),
        ('core', '0001_initial'),
        ('llm', '0002_llmbatch_agent_run_llmcall_agent_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reddit_id', models.CharField(max_length=20)),
                ('subreddit', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('body', models.TextField(blank=True)),
                ('url', models.URLField(max_length=1000)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('upvotes', models.IntegerField(default=0)),
                ('num_comments', models.IntegerField(default=0)),
                ('flair', models.CharField(blank=True, max_length=200)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('score_status', models.CharField(choices=[('pending', 'Pending'), ('scored', 'Scored'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('relevance_score', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('relevance_reason', models.TextField(blank=True)),
                ('reply_worthwhile', models.BooleanField(blank=True, null=True)),
                ('score_error', models.TextField(blank=True)),
                ('scored_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reddit_posts', to='agents.agentrun')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reddit_posts', to='core.project')),
                ('score_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='llm.llmcall')),
            ],
            options={
                'ordering': ['-fetched_at'],
                'constraints': [models.UniqueConstraint(fields=('project', 'reddit_id'), name='uniq_reddit_post')],
            },
        ),
    ]
