# Generated by Django 6.0.8 on 2026-09-19 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0002_externalusage'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('ai_initial', 'Ai Initial'), ('ai_regenerated', 'Ai Regenerated'), ('human_edit', 'Human Edit')], max_length=20)),
                ('content', models.JSONField()),
                ('nudge', models.CharField(blank=True, max_length=30)),
                ('instruction', models.TextField(blank=True)),
                ('prompt_name', models.CharField(blank=True, max_length=100)),
                ('prompt_version', models.CharField(blank=True, max_length=20)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['n'],
            },
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(max_length=20)),
                ('kind', models.CharField(choices=[('reddit_comment', 'Reddit Comment'), ('x_post', 'X Post'), ('x_thread', 'X Thread'), ('blog_post', 'Blog Post')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('posted', 'Posted'), ('dismissed', 'Dismissed')], db_index=True, default='new', max_length=20)),
                ('compliance_flags', models.JSONField(blank=True, default=list)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('posted_url', models.URLField(blank=True, max_length=1000)),
                ('dismiss_reason', models.CharField(blank=True, choices=[('not_relevant', 'Not Relevant'), ('already_answered', 'Already Answered'), ('too_promotional', 'Too Promotional'), ('other', 'Other')], max_length=30)),
                ('dismiss_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='agents.agentrun')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
