# Generated by Django 6.0.8 on 2026-09-19 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inbox', '0001_initial'),
        ('llm', '0002_llmbatch_agent_run_llmcall_agent_run'),
        ('reddit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='source_reddit_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='reddit.redditpost'),
        ),
        migrations.AddField(
            model_name='draftversion',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='inbox.draft'),
        ),
        migrations.AddField(
            model_name='draftversion',
            name='llm_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='llm.llmcall'),
        ),
        migrations.AddField(
            model_name='draft',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inbox.draftversion'),
        ),
        migrations.AddConstraint(
            model_name='draftversion',
            constraint=models.UniqueConstraint(fields=('draft', 'n'), name='uniq_draft_version_n'),
        ),
        migrations.AddIndex(
            model_name='draft',
            index=models.Index(fields=['project', 'status', '-created_at'], name='inbox_draft_project_801118_idx'),
        ),
    ]
