# Generated by Django 6.0.8 on 2026-09-19 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('inbox', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='blog_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='content.blogtopic'),
        ),
    ]
