# Generated by Django 6.0.8 on 2026-09-19 20:34

from django.db import migrations, models


def backfill(apps, schema_editor):
    Draft = apps.get_model("inbox", "Draft")
    for d in Draft.objects.filter(status="dismissed", dismissed_at__isnull=True):
        d.dismissed_at = d.updated_at
        d.save(update_fields=["dismissed_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0003_draft_blog_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
