# Generated by Django 6.0.8 on 2026-09-19 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anthropic_batch_id', models.CharField(max_length=100, unique=True)),
                ('task', models.CharField(max_length=100)),
                ('prompt_version', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('ended', 'Ended'), ('collected', 'Collected'), ('failed', 'Failed')], default='submitted', max_length=20)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('succeeded_count', models.PositiveIntegerField(default=0)),
                ('errored_count', models.PositiveIntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='LLMCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(db_index=True, max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('prompt_version', models.CharField(max_length=20)),
                ('prompt_hash', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('ok', 'Ok'), ('error', 'Error'), ('refused', 'Refused'), ('truncated', 'Truncated'), ('invalid_output', 'Invalid Output')], default='ok', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('stop_reason', models.CharField(blank=True, max_length=30)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cache_read_tokens', models.PositiveIntegerField(default=0)),
                ('cache_write_tokens', models.PositiveIntegerField(default=0)),
                ('web_search_requests', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('is_batch', models.BooleanField(default=False)),
                ('custom_id', models.CharField(blank=True, max_length=64)),
                ('request_id', models.CharField(blank=True, max_length=100)),
                ('langsmith_run_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='llm.llmbatch')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
