# Generated by Django 6.0.8 on 2026-09-19 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmbatch',
            name='agent_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_batches', to='agents.agentrun'),
        ),
        migrations.AddField(
            model_name='llmcall',
            name='agent_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_calls', to='agents.agentrun'),
        ),
    ]
